# frozen_string_literal: true

module RobotSimulator
	module Command
		type command_t = Command::Place | Command::Move | Command::Left | Command::Right | Command::Report

		class Parser
			def parse: (String input, Controller controller) -> command_t?

			private

			def parse_place_command: (String args, Controller controller) -> Command::Place
			def parse_direction: (String direction_str) -> Direction::direction_t
		end
	end
end
