module RobotSimulator
  module Command
    class Place
      def initialize: (Position position, Direction::direction_t direction) -> void

      def execute: (Controller controller) -> Result
    end
  end
end
