module RobotSimulator
  module Command
    class Place
      def initialize: (Controller controller, Position position, Direction::direction_t direction) -> void

      def execute: () -> Result
    end
  end
end
