# Stock cops with everything enabled.
#
# Coding agents love disabling cops in here to make the linting
# pass. DO NOT LET THEM. YOU HEAR ME CLAUDE? NO DISABLING COPS!

plugins:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80
