module RobotSimulator
  class Board
    attr_reader width: Integer
    attr_reader height: Integer

    def initialize: (Integer width, Integer height) -> void
    def valid?: (Position position) -> bool
  end
end