module RobotSimulator
  class CLI
    @parser: Command::StringParser

    def initialize: (Command::StringParser parser) -> void
    def read_command: () -> Command::command_t?
    def handle_result: (Command::Result result) -> void
  end
end