module RobotSimulator
  class Controller
    attr_reader robot: Robot?
    attr_reader board: Board

    def initialize: (Robot? robot, Board board) -> void

    def update_robot: (Robot robot) -> void
  end
end
