module RobotSimulator
  module Direction
    type direction_t = :north | :south | :east | :west

    NORTH: :north
    SOUTH: :south
    EAST: :east
    WEST: :west
    CLOCKWISE: Array[direction_t]

    def self.turn_right: (direction_t direction) -> direction_t
    def self.turn_left: (direction_t direction) -> direction_t
  end
end
