module RobotSimulator
  class Error < StandardError
  end

  class NoRobotPlacedError < Error
  end

  class RobotWouldFallError < Error
  end

  class ObstacleInTheWayError < Error
  end

  class RobotInTheWayError < Error
  end

  class ObstacleWouldFallError < Error
  end
end