module RobotSimulator
	class Position
		attr_reader x: Integer
		attr_reader y: Integer

		def initialize: (Integer x_coord, Integer y_coord) -> void
		def move: (Direction::direction_t direction) -> Position?

		private

		def warn_if_excessive_coordinates: () -> void
	end
end
