module RobotSimulator
  class RobotController
    attr_reader robot: Robot?
    attr_reader board: Board

    def initialize: (Robot? robot, Board board) -> void

    def execute_command: (Commands::Command command) -> Commands::Command
  end
end