module RobotSimulator
  class RobotController
    attr_reader robot: Robot?
    attr_reader board: Board

    def initialize: (Robot robot, Board board) -> void

    def move_robot: () -> Command

    def turn_robot_left: () -> Command

    def turn_robot_right: () -> Command
  end
end