module RobotSimulator
  class Simulator
    attr_reader board: Board
    attr_reader robot: Robot?

    def initialize: (Integer width, Integer height) -> void

    def place_robot: (Position position, Direction::direction_t direction) -> void

    def move_robot: () -> Command::Result

    def turn_left: () -> Command::Result

    def turn_right: () -> Command::Result
  end
end
